[ids]
*

[meta]
a = C-a
b = C-b
c = C-c
f = C-f
i = C-i
k = C-k
l = C-l
m = C-m
n = C-n
o = C-o
p = C-p
r = C-r
s = C-s
t = C-t
u = C-u
v = C-v
w = C-w
x = C-x
y = C-y
z = C-z
- = C--
= = C-=
left = home
right = end

